/**
 * @see https://unsplash.com/explore
 */
export default {
    'business': 'Business',
    'coffee': 'Coffee',
    'nature': 'Nature',
    'love': 'Love',
    'team': 'Team',
    'health': 'Health',
    'space': 'Space',
    'social-media': 'Social Media',
    'computer': 'Computer',
    'girl': 'Girl',
    'food': 'Food',
    'people': 'People',
    'work': 'Work',
    'office': 'Office',
    'music': 'Music',
    'landscape': 'Landscape',
    'family': 'Family',
    'couple': 'Couple',
    'pug': 'Pug',
    'canada': 'Canada',
    'wedding': 'Wedding',
    'bike': 'Bike',
    'Laptop': 'Laptop',
    'rain': 'Rain',
    'fitness': 'Fitness',
    'new-york': 'New York',
    'autumn': 'Autumn',
    'desk': 'Desk',
    'Flowers': 'Flowers',
    'women': 'Women',
    'clothing': 'Clothing',
    'happy': 'Happy',
    'clock': 'Clock',
    'iphone': 'iPhone',
    'road': 'Road',
    'yoga': 'Yoga',
    'man': 'Man',
    'home': 'Home',
    'tree': 'Tree',
    'mountains': 'Mountains',
    'city': 'City',
    'summer': 'Summer',
    'nasa': 'NASA',
    'feet': 'Feet',
    'friends': 'Friends',
    'shopping': 'Shopping',
    'japan': 'Japan',
    'typewriter': 'Typewriter',
    'house': 'House',
    'restaurant': 'Restaurant',
    'sky': 'Sky',
    'watch': 'Watch',
};
